const funnel=window.FUNNEL_DATA;
function trackMeta(event,params){if(typeof window.fbq==='function')window.fbq('track',event,params||{});}
const CHECKOUT_URL='https://payment.ticto.app/O7568BD52';
const app=document.querySelector('#app');
const state={step:0,history:[],answers:{peso:70,altura:180,ideal:70,areasalvo:[]},selected:{},loadingTimer:null,carouselTimers:[],notificationTimer:null,trackedStep:null,quizCompleted:false};
const checkSvg='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M20 6 9 17l-5-5"/></svg>';
const backSvg='<svg viewBox="0 0 448 512" fill="currentColor"><path d="M229.9 473.899l19.799-19.799c4.686-4.686 4.686-12.284 0-16.971L94.569 282H436c6.627 0 12-5.373 12-12v-28c0-6.627-5.373-12-12-12H94.569l155.13-155.13c4.686-4.686 4.686-12.284 0-16.971L229.9 38.101c-4.686-4.686-12.284-4.686-16.971 0L3.515 247.515c-4.686 4.686-4.686 12.284 0 16.971L212.929 473.9c4.686 4.686 12.284 4.686 16.971-.001z"></path></svg>';

function cleanTimers(){if(state.loadingTimer)clearInterval(state.loadingTimer);state.loadingTimer=null;for(const t of state.carouselTimers)clearInterval(t);state.carouselTimers=[];if(state.notificationTimer)clearInterval(state.notificationTimer);state.notificationTimer=null}
function html(value=''){return interpolate(String(value)).replace(/&nbsp;|\u00a0/g,' ')}
function strip(value=''){const d=document.createElement('div');d.innerHTML=html(value);return d.textContent.trim()}
function variables(){return{peso:Number(state.answers.peso||70),altura:Number(state.answers.altura||180),ideal:Number(state.answers.ideal||70),areasalvo:Array.isArray(state.answers.areasalvo)?state.answers.areasalvo.join(', '):(state.answers.areasalvo||'')}}
function evaluateCalc(expression){const vars=variables();let value=String(expression||'').trim();if(value.startsWith('calc(')&&value.endsWith(')'))value=value.slice(5,-1);value=value.replace(/\{\{([^}]+)\}\}/g,(_,key)=>Number(vars[key.trim()]||0));if(!/^[\d+\-*/().\s]+$/.test(value))return 0;try{return Function(`"use strict";return (${value})`)()}catch{return 0}}
function expandCalcs(value){const source=String(value);let out='',cursor=0;while(true){const start=source.indexOf('calc(',cursor);if(start<0){out+=source.slice(cursor);break}out+=source.slice(cursor,start);let depth=1,end=start+5;for(;end<source.length&&depth;end++){if(source[end]==='(')depth++;else if(source[end]===')')depth--}if(depth){out+=source.slice(start);break}const calc=source.slice(start,end);out+=Number(evaluateCalc(calc)).toFixed(2);cursor=end}return out}
function interpolate(value){const vars=variables();return expandCalcs(value).replace(/\{\{([^}]+)\}\}/g,(_,key)=>vars[key.trim()]??'')}
function roleMatches(layer){if(!layer.roles?.length)return true;return layer.roles.some(group=>group.every(rule=>{const actual=String(rule.variable).startsWith('calc(')?evaluateCalc(rule.variable):variables()[String(rule.variable).replace(/[{}]/g,'')]||0;const expected=Number(rule.value);switch(rule.compare){case'<':return actual<expected;case'<=':return actual<=expected;case'>':return actual>expected;case'>=':return actual>=expected;case'=':case'==':return actual==expected;default:return true}}))}
function basis(layer){const b=layer.design?.basis;return b?`style="flex-basis:${Number(b)}%"`:''}
function layerClass(layer){return `layer layer-${layer.type}${layer.design?.horizontalAlign==='mx-auto'?' center':''}`}
function media(src,width,height,contain=false,alt='Imagem'){if(!src)return'';const ratio=width&&height?height/width*100:100;return `<div class="image-box ${contain?'contain':''}" style="padding-bottom:${ratio}%"><img src="${src}" alt="${alt}" loading="eager"></div>`}
function header(){const pct=((state.step+1)/funnel.steps.length)*100;const logo=funnel.design.logo.src;return `<div class="topbar"><div class="back-wrap">${state.step?`<button class="back" data-action="back" aria-label="Voltar">${backSvg}<span></span></button>`:''}</div><div class="logo-mobile">${media(logo,funnel.design.logo.width,funnel.design.logo.height)}</div><div class="top-spacer"></div></div><div class="header-center"><div class="logo-desktop">${media(logo,funnel.design.logo.width,funnel.design.logo.height)}</div><div class="progress"><i style="width:${pct}%"></i></div></div>`}
function renderText(layer){const story=strip(layer.content.text).includes('Histórias Reais de Transformação')?' story-title':'';return `<div class="rich${story}">${html(layer.content.text)}</div>`}
function renderImage(layer){const image=layer.content.image||{};return `<div class="image-component">${media(image.src,image.width,image.height,layer.design?.fit==='contain')}</div>`}
function renderButton(layer){const success=layer.design?.style==='success'?' success':'';const pulse=layer.content?.type==='redirect'?' pulse':'';const c=layer.content;const destination=c.type==='redirect'?CHECKOUT_URL:(c.destination||'next');return `<button class="primary-btn${success}${pulse}" data-button-type="${c.type||'next'}" data-destination="${destination}">${c.label||'Continuar'}</button>`}
function alertStyle(layer){const s=layer.design?.style;return ['danger','success','warning','info','theme'].includes(s)?s:''}
function renderAlert(layer){const compact=layer.design?.padding==='p-2'?' compact':'';return `<div class="alert ${alertStyle(layer)}${layer.design?.contrast?' contrast':''}${compact}"><div class="rich">${html(layer.content.text)}</div></div>`}
function optionKey(layer){return layer.content.name||layer.content.id}
function renderOptions(layer){
  const vertical=layer.design?.orientation==='vertical';
  const cols=layer.design?.grid==='grid-cols-2'?' cols-2':'';
  const compactEnd=layer.content.introType==='text'?' compact-end':'';
  const key=optionKey(layer);
  const selected=state.selected[key]||[];
  const items=layer.content.options.map(option=>{
    const active=selected.includes(option.id);
    const source=option.image;
    let mediaHtml='';
    let mediaKind='no-media';
    if(source&&typeof source==='object'&&source.type==='emoji'&&source.src){
      mediaHtml=`<div class="option-emoji">${source.src}</div>`;
      mediaKind='has-emoji';
    }else if(source&&typeof source==='object'&&source.src){
      mediaHtml=vertical?`<div class="option-media-square"><img src="${source.src}" alt="Imagem"></div>`:`<div class="option-thumb"><img src="${source.src}" alt="Imagem"></div>`;
      mediaKind='has-image';
    }else if(typeof source==='string'&&source){
      mediaHtml=`<div class="option-emoji">${source}</div>`;
      mediaKind='has-emoji';
    }
    const check=layer.design?.icon==='none'?'':`<span class="check">${checkSvg}</span>`;
    const row=`<div class="option-row">${!vertical?mediaHtml:''}<div class="option-label">${html(option.label)}</div>${check}</div>`;
    return `<div class="option-item"><button class="option ${vertical?'vertical':'horizontal'} ${mediaKind}${active?' active':''}" data-option-layer="${layer.id}" data-option-key="${key}" data-option-id="${option.id}" data-option-label="${encodeURIComponent(strip(option.label))}">${vertical?mediaHtml:''}${row}</button></div>`;
  }).join('');
  return `<div class="options${cols}${compactEnd}">${items}</div>`;
}
function renderMeasure(layer,unit,min,max){const key=layer.content.name;const value=Number(state.answers[key]??layer.content.value);const ticks=Array.from({length:31},(_,i)=>`<i class="${i%5===0?'major':''}"></i>`).join('');return `<div class="unit-toggle"><button class="active">${unit}</button><button>${unit==='kg'?'lb':'pol'}</button></div><div class="ruler"><div class="ruler-stage"><div class="ruler-value" data-value-for="${key}">${value}<small>${unit}</small></div><div class="ruler-ticks">${ticks}</div><div class="ruler-labels" data-labels-for="${key}"><span>${value-10}</span><span>${value}</span><span>${value+10}</span></div><div class="ruler-pointer"></div><input type="range" min="${min}" max="${max}" value="${value}" data-measure="${key}" data-unit="${unit}" aria-label="${unit==='kg'?'Peso':'Altura'}"></div><div class="ruler-help">Arraste para ajustar</div></div>`}
function renderAudio(layer){const c=layer.content;const id=`audio-${layer.id}`;const heights=[10,14,18,25,20,14,24,30,19,12,17,26,32,22,14,20,28,18,12,16,25,31,23,15,11,19,27,21,14,10];const waveform=heights.map(h=>`<i style="height:${h}px"></i>`).join('');return `<div class="audio-card"><div class="audio-pattern"></div><div class="audio-bubble"><div class="audio-sender">${c.sender||'Fabiana Santos'}</div><div class="audio-controls"><button class="audio-play" data-audio="${id}" aria-label="Reproduzir áudio"><svg viewBox="0 0 24 24" fill="currentColor"><path d="M8 5v14l11-7z"></path></svg></button><div class="audio-wave-zone"><div class="audio-wave">${waveform}</div><input type="range" min="0" max="100" value="0" data-audio-range="${id}" aria-label="Progresso do áudio"><span class="audio-time" data-audio-time="${id}">--:--</span></div><div class="audio-avatar-wrap"><img class="audio-avatar" src="${c.image?.src||''}" alt="${c.sender||'Áudio'}"><span>🎙</span></div></div></div><audio id="${id}" preload="metadata" src="${c.audio?.src||''}"></audio></div>`}
function renderQuotes(layer){const grid=layer.content.layout==='grid'?' grid':'';return `<div class="quotes${grid}">${layer.content.quotes.map(q=>`<article class="quote">${q.image?.src?`<img class="quote-avatar" src="${q.image.src}" alt="${q.name||''}">`:''}<div class="quote-main">${Number(q.rate)>0?`<div class="stars">${'★'.repeat(Number(q.rate))}</div>`:''}<div class="quote-name">${html(q.name||'')}</div>${q.activity?`<div class="quote-activity">${html(q.activity)}</div>`:''}<p class="quote-text">${html(q.text||'')}</p></div></article>`).join('')}</div>`}
function renderMetric(layer){const c=layer.content;const percent=Math.max(4,Math.min(96,Number(c.percent||30)));const segments=['#14b8a6,#a5c368','#a5c368,#facc15','#facc15,#facc15','#facc15,#e96827','#e96827,#dc2626'].map(colors=>`<i style="background:linear-gradient(to right,${colors})"></i>`).join('');return `<div class="metric-card"><div class="metric-copy"><div><div class="metric-title">${html(c.title||'')}</div>${c.subtitle?`<div class="metric-sub">${html(c.subtitle)}</div>`:''}</div></div><div class="metric-tooltip-space" style="width:${percent}%"><div class="metric-tooltip">${c.tooltip||'Você'}</div></div><div class="metric-track"><div class="metric-segments">${segments}</div><i class="metric-dot" style="left:${percent}%"></i></div>${c.legends?`<div class="metric-legends">${c.legends.split(',').map(x=>`<span>${x.trim()}</span>`).join('')}</div>`:''}</div>`}
function renderClear(layer){const match=String(layer.content.clear||'').match(/([\d.]+)rem/);return `<div style="height:${match?match[1]:'1'}rem"></div>`}
function renderCarousel(layer){const id=`carousel-${layer.id}`;const items=layer.content.items||[];return `<div class="carousel" id="${id}" data-delay="${Number(layer.content.delay||3)*1000}"><div class="carousel-track">${items.map(item=>`<div class="slide">${item.image?.src?`<img src="${item.image.src}" alt="Imagem">`:''}</div>`).join('')}</div>${layer.content.pagination?`<div class="dots">${items.map((_,i)=>`<i class="${i?'':'active'}"></i>`).join('')}</div>`:''}</div>`}
function renderArguments(layer){const one=layer.content.cols==='grid-cols-1'?' one-col':'';return `<div class="arguments${one}">${layer.content.arguments.map(item=>`<article class="argument">${item.image?.src?`<img src="${item.image.src}" alt="">`:''}<div class="rich">${html(item.text)}</div></article>`).join('')}</div>`}
function renderPrice(layer){const c=layer.content,value=String(c.value||'').replace(/^R\$\s*/, '<span>R$</span> ');return `<div class="price">${c.featured?`<div class="price-featured">${c.featured}</div>`:''}<div class="price-body"><div class="price-title">${html(c.title||'')}</div><div class="price-amount"><div class="price-before">${c.before||''}</div><div class="price-value">${value}</div>${c.after?`<div class="price-after">${c.after}</div>`:''}</div></div></div>`}
function renderVideo(layer){const ratio=layer.design?.ratio==='mobile'?'mobile':'wide';const stored=layer.content.video||'';const origin=/^https?:$/.test(location.protocol)?`&origin=${encodeURIComponent(location.origin)}`:'';let video=stored;if(stored.includes('ZUFTwMp5F5c'))video=`<iframe width="560" height="315" src="https://www.youtube.com/embed/ZUFTwMp5F5c?si=9yEcBt9dn3GkZxsu${origin}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`;if(stored.includes('EudZGrEhmQg'))video=`<iframe width="560" height="315" src="https://www.youtube.com/embed/EudZGrEhmQg?si=Y0oDhgm7jvRG51kL${origin}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`;return `<div class="video ${ratio}">${video}</div>`}
function renderGraphics(layer){return `<div class="graphics">${layer.content.graphics.map(g=>{const color=g.customColor||(g.style==='theme'?'var(--theme)':g.style)||'var(--theme)';return `<div class="graphic"><div class="graphic-meter"><div class="graphic-percent">${g.percent}%</div><i style="height:${g.percent}%;background:${color}"></i></div><div class="graphic-legend">${html(g.legend||'')}</div></div>`}).join('')}</div>`}
function renderTimer(layer){return `<div class="timer" data-timer="${Number(layer.content.time||600)}"><div class="timer-box"><strong data-timer-min>10</strong><span>min</span></div><b class="timer-sep">:</b><div class="timer-box"><strong data-timer-sec>00</strong><span>seg</span></div></div>`}
function renderFaq(layer){return `<div class="faq">${layer.content.questions.map((q,i)=>`<details ${i===0&&layer.content.firstQuestionOpened?'open':''}><summary>${q.question}</summary><div class="faq-answer">${html(q.answer)}</div></details>`).join('')}</div>`}
function renderNotification(layer){const vars=layer.content.variables?.[0]?.values?.filter(Boolean)||[];if(!vars.length)return'';return `<div class="notification" data-notification='${encodeURIComponent(JSON.stringify(vars))}'><strong>${html(layer.content.title).replace('@1',vars[0])}</strong>${html(layer.content.text)}</div>`}
function renderLayer(layer){if(!roleMatches(layer))return'';let body='';switch(layer.type){case'text':body=renderText(layer);break;case'image':body=renderImage(layer);break;case'button':body=renderButton(layer);break;case'alert':body=renderAlert(layer);break;case'options':body=renderOptions(layer);break;case'audio':body=renderAudio(layer);break;case'quotes':body=renderQuotes(layer);break;case'weight':body=renderMeasure(layer,'kg',40,250);break;case'height':body=renderMeasure(layer,'cm',140,220);break;case'clear':body=renderClear(layer);break;case'metric':body=renderMetric(layer);break;case'carousel':body=renderCarousel(layer);break;case'arguments':body=renderArguments(layer);break;case'price':body=renderPrice(layer);break;case'video':body=renderVideo(layer);break;case'graphics':body=renderGraphics(layer);break;case'timer':body=renderTimer(layer);break;case'faq':body=renderFaq(layer);break;case'notification':body=renderNotification(layer);break;case'loading':return'';default:return''}return `<div class="${layerClass(layer)}" ${basis(layer)}>${body}</div>`}
function loadingScreen(step){let loadIndex=0;return step.layers.map(layer=>{if(layer.type==='loading'){const index=loadIndex++;return `<div class="layer layer-loading"><div class="loading-item${index?' hidden':''}" data-loading-item="${index}"><div class="loading-line"><span>${layer.content.title||'Analisando...'}</span><span data-loading-percent="${index}">0%</span></div><div class="loading-track"><i data-loading-bar="${index}"></i></div></div></div>`}return renderLayer(layer)}).join('')}
function trackQuizStep(){const analytics=window.FunnelAnalytics,currentStep=state.step+1,total=funnel.steps.length;if(!analytics)return;analytics.setState({current_step:currentStep,quiz_total_steps:total});if(state.trackedStep!==currentStep){state.trackedStep=currentStep;analytics.event('quiz_step',{step:currentStep,total_steps:total});analytics.heartbeat()}if(currentStep===total&&!state.quizCompleted){state.quizCompleted=true;analytics.event('quiz_completed',{total_steps:total})}}
function render(){cleanTimers();const step=funnel.steps[state.step];const isOffer=step.title==='oferta';document.documentElement.style.setProperty('--theme',funnel.design.themeColor||'#16a34a');document.documentElement.style.setProperty('--text',funnel.design.contentColor||'#6b7280');document.documentElement.style.setProperty('--title',funnel.design.titleColor||'#030712');document.documentElement.style.setProperty('--bg',funnel.design.backgroundColor||'#fff');const layers=step.title==='carregando'?loadingScreen(step):step.layers.map(renderLayer).join('');app.innerHTML=`<div class="fade-in"><div class="main-content${isOffer?' offer-step':''}">${header()}<div class="content-wrap"><div class="layers">${layers}</div></div><div class="bottom-space"></div></div></div>`;if(isOffer)trackMeta('ViewContent',{content_name:'Página de oferta Mounjaro de Pobre'});bind();trackQuizStep();window.scrollTo({top:0,behavior:'instant'});if(step.title==='carregando')startLoading(step);startCarousels();startNotification();startTimers()}
function goNext(){if(state.step>=funnel.steps.length-1)return;state.history.push(state.step);state.step++;render()}
function goBack(){if(!state.history.length)return;state.step=state.history.pop();render()}
function bind(){app.querySelector('[data-action="back"]')?.addEventListener('click',goBack);app.querySelectorAll('[data-button-type]').forEach(btn=>btn.addEventListener('click',()=>{const type=btn.dataset.buttonType,dest=btn.dataset.destination;if(type==='redirect'&&dest&&dest!=='next'){window.FunnelAnalytics?.event('cta_clicked',{location:'quiz_offer'});trackMeta('InitiateCheckout',{content_name:'Checkout Mounjaro de Pobre'});window.location.href=dest;return}goNext()}));app.querySelectorAll('[data-option-id]').forEach(btn=>btn.addEventListener('click',()=>selectOption(btn)));app.querySelectorAll('[data-measure]').forEach(input=>{const update=value=>{value=Math.max(Number(input.min),Math.min(Number(input.max),Math.round(value)));input.value=value;const key=input.dataset.measure,unit=input.dataset.unit;state.answers[key]=value;app.querySelector(`[data-value-for="${key}"]`).innerHTML=`${value}<small>${unit}</small>`;const labels=app.querySelectorAll(`[data-labels-for="${key}"] span`);[value-10,value,value+10].forEach((n,i)=>{if(labels[i])labels[i].textContent=n})};let drag=null;input.addEventListener('input',()=>update(Number(input.value)));input.addEventListener('pointerdown',event=>{event.preventDefault();drag={x:event.clientX,value:Number(input.value)};input.setPointerCapture(event.pointerId);input.classList.add('dragging')});input.addEventListener('pointermove',event=>{if(!drag)return;const pixelsPerUnit=input.clientWidth/40;update(drag.value+(drag.x-event.clientX)/pixelsPerUnit)});const finish=event=>{if(!drag)return;drag=null;input.classList.remove('dragging');if(input.hasPointerCapture(event.pointerId))input.releasePointerCapture(event.pointerId)};input.addEventListener('pointerup',finish);input.addEventListener('pointercancel',finish)});app.querySelectorAll('[data-audio]').forEach(btn=>btn.addEventListener('click',()=>toggleAudio(btn)));app.querySelectorAll('[data-audio-range]').forEach(range=>range.addEventListener('input',()=>{const audio=document.getElementById(range.dataset.audio);if(audio.duration)audio.currentTime=audio.duration*Number(range.value)/100}));app.querySelectorAll('audio').forEach(audio=>{const showDuration=()=>{const time=app.querySelector(`[data-audio-time="${audio.id}"]`);if(time&&audio.duration)time.textContent=formatTime(audio.duration)};audio.addEventListener('loadedmetadata',showDuration);if(audio.readyState)showDuration()})}
function selectOption(btn){const layerId=btn.dataset.optionLayer,key=btn.dataset.optionKey,id=btn.dataset.optionId,label=decodeURIComponent(btn.dataset.optionLabel);const step=funnel.steps[state.step];const hasContinue=step.layers.some(l=>l.type==='button');const arr=state.selected[key]||[];if(hasContinue){const index=arr.indexOf(id);if(index>=0)arr.splice(index,1);else arr.push(id);state.selected[key]=arr;state.answers[key]=arr.map(selected=>{for(const l of step.layers.filter(x=>x.type==='options')){const o=l.content.options.find(x=>x.id===selected);if(o)return strip(o.label)}return selected});btn.classList.toggle('active')}else{state.selected[key]=[id];state.answers[key]=label;btn.classList.add('active');setTimeout(goNext,220)}}
function toggleAudio(btn){const audio=document.getElementById(btn.dataset.audio);const playIcon='<svg viewBox="0 0 24 24" fill="currentColor"><path d="M8 5v14l11-7z"></path></svg>';const pauseIcon='<svg viewBox="0 0 24 24" fill="currentColor"><path d="M6 5h4v14H6zm8 0h4v14h-4z"></path></svg>';if(audio.paused){audio.play();btn.innerHTML=pauseIcon}else{audio.pause();btn.innerHTML=playIcon}audio.ontimeupdate=()=>{const range=app.querySelector(`[data-audio-range="${audio.id}"]`),time=app.querySelector(`[data-audio-time="${audio.id}"]`);if(audio.duration)range.value=audio.currentTime/audio.duration*100;time.textContent=formatTime(audio.currentTime)};audio.onended=()=>{btn.innerHTML=playIcon}}
function formatTime(value){const n=Math.max(0,Math.floor(value||0));return`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function startLoading(step){const loads=step.layers.filter(l=>l.type==='loading');let elapsed=0,total=loads.reduce((max,l)=>Math.max(max,Number(l.content.starts??l.effects?.starts??0)+Number(l.content.seconds||0)),0)||6;state.loadingTimer=setInterval(()=>{elapsed+=.1;loads.forEach((load,index)=>{const starts=Number(load.content.starts??load.effects?.starts??0),seconds=Number(load.content.seconds||2),item=app.querySelector(`[data-loading-item="${index}"]`);if(elapsed>=starts){item?.classList.remove('hidden');const pct=Math.min(100,Math.max(0,Math.round((elapsed-starts)/seconds*100)));const percent=app.querySelector(`[data-loading-percent="${index}"]`),bar=app.querySelector(`[data-loading-bar="${index}"]`);if(percent)percent.textContent=pct+'%';if(bar)bar.style.width=pct+'%'}});if(elapsed>=total){clearInterval(state.loadingTimer);state.loadingTimer=null;setTimeout(goNext,250)}},100)}
function startCarousels(){app.querySelectorAll('.carousel').forEach(carousel=>{let index=0;const slides=carousel.querySelectorAll('.slide'),track=carousel.querySelector('.carousel-track');if(slides.length<2)return;const position=()=>{const width=carousel.clientWidth,slide=width*.9;track.style.transform=`translateX(${(width-slide)/2-index*(slide+8)}px)`;carousel.querySelectorAll('.dots i').forEach((dot,i)=>dot.classList.toggle('active',i===index))};position();const delay=Number(carousel.dataset.delay||3000);const timer=setInterval(()=>{index=(index+1)%slides.length;position()},delay);state.carouselTimers.push(timer)})}
function startNotification(){const box=app.querySelector('[data-notification]');if(!box)return;const values=JSON.parse(decodeURIComponent(box.dataset.notification));let i=0;state.notificationTimer=setInterval(()=>{i=(i+1)%values.length;box.querySelector('strong').textContent=values[i]},20000)}
function startTimers(){app.querySelectorAll('[data-timer]').forEach(clock=>{let seconds=Number(clock.dataset.timer);const update=()=>{clock.querySelector('[data-timer-min]').textContent=String(Math.floor(seconds/60)).padStart(2,'0');clock.querySelector('[data-timer-sec]').textContent=String(seconds%60).padStart(2,'0');seconds=Math.max(0,seconds-1)};update();const timer=setInterval(()=>{update();if(seconds<=0)clearInterval(timer)},1000);state.carouselTimers.push(timer)})}
window.FunnelAnalytics?.event('quiz_started',{total_steps:funnel.steps.length});
render();
